[package]
name = "timer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7.0"
user32-sys = "0.2.0"
winapi = { version = "0.3.9", features = ["winuser"] }
